### ISSUE TITLE
Why do we have a Code of Conduct?

### ISSUE THREAD

**Issue by quevangel** [daque-dev/viare#10]

**Comment by davidomarf** [comment]
Community paperwork.

**Comment by quevangel** [comment]
Community paperwork?

**Comment by quevangel** [comment]
> Community paperwork.

This comment is against my personal Code of Conduct.

**Comment by davidomarf** [comment]
For the sake of our stats.
https://github.com/daque-dev/viare/community

**Comment by quevangel** [comment]
And what are the stats for?

**Comment by quevangel** [comment]
**THIS IS MADNESS**

**Comment by davidomarf** [comment]
Self-esteem and self-worth. (✿◕‿◕)

**Comment by davidomarf** [comment]
https://opensource.guide/

Also, contribute section has a nice squirrel.

**Comment by quevangel** [comment]
You should be retro-actively aborted.

**Comment by davidomarf** [comment]
> Enforces current Code of Conduct. 
> **Bans him**

**Comment by quevangel** [comment]
> ViaRE dies but dies according to it's Code of Conduct so it's all good.

**Comment by davidomarf** [comment]
Great, we all can agree on that.

**Comment by davidomarf** [comment]
Taking this more seriously, I think it's just better to have it, than not having it.

**Comment by quevangel** [comment]
Okay. I still cannot see how it can benefit us. But I agree.
