### ISSUE TITLE
CONTRIBUTING.md should be general to both projects.

### ISSUE THREAD

**Issue by quevangel** [daque-dev/viare#11]
Everything that is mentioned in CONTRIBUTING.md also applies to libdaque and may as well apply to any other project we do, so why don't we create a repository hosting our contributing principles and only refer to it from viare's or libdaque's CONTRIBUTING.md?

**Comment by davidomarf** [comment]
Yes. It does so far.

But ViaRE will deal with more information eventually. And will require a broader set of contributions: UI/UX, Music, Story, Design, etc. and ViaRE's CONTRIBUTING.md file will be modified when required.

**Comment by quevangel** [comment]
Wouldn't it be good any way to have something like a general CONTRIBUTING.md? 
And only do the extra additions in ViaRE's CONTRIBUTING.md.

**Comment by davidomarf** [comment]
Discussion in personal meeting arrived at the conclusion that we'd keep CONTRIBUTING.md files in all projects even if they're the same, I can recall.

This to treat every repository apart from the others. 

So can we close this?

**Comment by quevangel** [comment]
Yes.
