### ISSUE TITLE
Rendering of the default random height map shows a black screen in Windows' systems

### ISSUE THREAD

**Issue by quevangel** [daque-dev/viare#5]
## Observed Behavior
The rendering results in a black screen in Windows' systems.

## Affected systems and Probable Issue Location
Both of our current Windows' ViaRE development setups (quevangel and davidomarf) are affected.
Because of this, the issue is likely to be only about Windows and not hardware as it was recently suggested by David.

**Comment by davidomarf** [comment]
I'll close this for now.

Reopen if, once #8 gets solved, this issue is still causing troubles.
