### ISSUE TITLE
Can't compile with current develop version of libdaque

### ISSUE THREAD

**Issue by quevangel** [daque-dev/viare#8]
There are symbols currently used in ViaRE which are no longer defined in libdaque.
In particular some Shader-related stuff previously defined in daque.graphics which is now handled by a completely different API defined in daque.graphics.glsl.

**Comment by quevangel** [comment]
## Known Solution: 
Refactor heightmap-perspective-testing code to use the new API.

**Comment by davidomarf** [comment]
I'm not that related with the API of libdaque. 

I'd fix this, and at the same time, start documenting how to use libdaque's API.

**Comment by quevangel** [comment]
There is an example use in the unittest section of the daque.graphics.glsl which you can read at https://github.com/daque-dev/libdaque/blob/develop/source/daque/graphics/glsl.d#L754, @davidomarf. :)

**Comment by davidomarf** [comment]
Would it be appropiate to discard the tests instead of fixing them?

**Comment by quevangel** [comment]
I think it would be appropiate. Let's do this.

**Comment by quevangel** [comment]
**Done**.
